server:
  port: 8000
spring:
  application:
    name: Comsumer-Login
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# hystrix熔断器，10秒后自动超时
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
      circuitBreaker:
        errorThresholdPercentage: 50
        sleepWindowInMilliseconds: 10000
        requestVolumeThreshold: 10
